---
- name: Install nginx
  apt:
    pkg: nginx
    state: latest
    force: yes

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart nginx