---
# Note: Debian9 has certbot in the official PPAs
- name: add certbot ppa
  apt_repository:
    repo: ppa:certbot/certbot
  when: ansible_distribution == 'Ubuntu'

- name: install certbot
  apt:
    name: certbot
    state: latest

- name: "check if ssl certs for {{ domains | join(',') }} are already generated"
  stat:
    path: "/etc/letsencrypt/live/{{ domains | first }}/fullchain.pem"
  register: fullchain

- name: stop nginx
  service:
    name: nginx
    state: stopped
  when: not fullchain.stat.exists

- name: "generate ssl certificates for {{ domains | join(',') }}"
  command: "certbot certonly --standalone --email {{ email }}
       --agree-tos -n -d {{ domains | join(',') }}{% if ssl_staging %} --staging{% endif %}"
  when: not fullchain.stat.exists

- name: create a cron job to autorenew all ssl certificates
  cron:
    name: auto renew the ssl certificates
    minute: 1
    hour: 23
    weekday: 0
    job: '/usr/bin/certbot renew --quiet --pre-hook "systemctl stop nginx.service" --post-hook "systemctl start nginx.service"'
