---

- name: install certbot
  apt:
    name: certbot
    state: latest

# - name: check if dh group already generated
#   stat:
#     path: /etc/ssl/certs/dhparam.pem
#   register: dhparam

# - name: generate dh group
#   raw: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
#   when: not dhparam.stat.exists

- name: "check if ssl certs for {{ domain }} are already generated"
  stat:
    path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
  register: fullchain

- name: stop nginx
  service:
    name: nginx
    state: stopped
  when: not fullchain.stat.exists


- name: "generate staging ssl certificates for {{ domain }}"
  command: "certbot certonly --standalone --email {{ email }}
       --agree-tos -n -d {{ domain }},www.{{ domain }} --staging"
  when:
    - not fullchain.stat.exists
    - ssl == 'staging'
  register: ssl_staging

- name: "generate ssl certificates for {{ domain }}"
  command: "certbot certonly --standalone --email {{ email }}
       --agree-tos -n -d {{ domain }},www.{{ domain }}"
  when:
    - not fullchain.stat.exists
    - ssl != 'staging'

- name: create a cron job to autorenew all ssl certificates
  cron:
    name: auto renew the ssl certificates
    minute: 1
    hour: 23
    weekday: 0
    job: '/usr/bin/certbot renew --quiet --renew-hook "/usr/sbin/service nginx reload"'