sudo: required

language: python

python:
  - "3.5"

services:
  - docker

before_install:
  - echo "${ANSIBLE_VAULT_PASSWORD}" > .pass
  - docker pull geerlingguy/docker-ubuntu1604-ansible


script:
  - docker run -h testserver -t -i -v $PWD:/data geerlingguy/docker-ubuntu1604-ansible /data/run_tests.sh
