---
- name: deploy sir-bot-a-lot
  hosts: sirbot
  vars:
    username: "{{ sirbot_user }}"
    domain: "{{ sirbot_domain }}"
    service_name: sirbot
    site_port: "{{ sirbot_port }}"
    exec_start: "/home/{{ username }}/.pyvenv/bin/sirbot -c {{ sirbot_config }}"
    work_dir: "/home/{{ username }}/"
    service_environment:
      - "SIRBOT_SLACK_BOT_TOKEN={{ SIRBOT_SLACK_BOT_TOKEN }}"
      - "SIRBOT_SLACK_TOKEN={{ SIRBOT_SLACK_TOKEN }}"
      - "SIRBOT_SLACK_VERIFICATION_TOKEN={{ SIRBOT_SLACK_VERIFICATION_TOKEN }}"
      - "SIRBOT_GITHUB_SECRET={{ SIRBOT_GITHUB_SECRET }}"
  roles:
    - user
    - nginx
    - sirbot
    - role: system_service
      when: systemd_enabled == true
