---
ansible_ssh_host: 164.132.88.113
ansible_ssh_port: 22
ansible_ssh_user: root
email: pythondev.slack@gmail.com
base_domain: pyslackers.com

website_domain: "{{ base_domain }}"
website_port: 3000
website_user: website
website_version: prod

sirbot_user: sirbot
sirbot_port: 8080
sirbot_config: /home/sirbot/sirbot-pythondev/sirbot.yml
sirbot_domain: "sirbot.{{ base_domain }}"
