- name: "Install python {{ python_version }}"
  command: "/usr/local/pythonz/bin/pythonz install {{ python_version }}"
  args:
    creates: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/python"

- name: "Install virtualenv"
  pip:
    executable: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/pip3"
    name: virtualenv
    state: latest