- name: "Download python source"
  get_url:
    url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: "/usr/local/pythonz/Python-{{ python_version }}.tgz"
    mode: 0440

- name: "Install python"
  command: "/usr/local/pythonz/bin/pythonz install --file /usr/local/pythonz/Python-{{ python_version }}.tgz  {{ python_version }}"
  args:
    creates: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/python"

- name: "Install virtualenv"
  pip:
    executable: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/pip3"
    name: virtualenv
    state: latest