- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: stop nginx
  service:
    name: nginx
    state: stopped

- name: start nginx
  service:
    name: nginx
    state: started

- name: reload nginx
  service:
    name: nginx.service
    state: reloaded
  when: "enabled_sites.changed"
