---

- name: Clone core repo
  become: true
  become_user: sirbot
  git:
    accept_hostkey: yes
    clone: yes
    repo: https://github.com/pyslackers/sir-bot-a-lot.git
    version: master
    dest: /home/sirbot/sir-bot-a-lot
    force: yes
    remote: origin
  register: sirbot_clone_core
  notify:
    - Restart sirbot

- name: Clone plugin repo
  become: true
  become_user: sirbot
  git:
    accept_hostkey: yes
    force: yes
    clone: yes
    repo: https://github.com/pyslackers/sirbot-plugins.git
    version: master
    dest: /home/sirbot/sirbot-plugin
  register: sirbot_clone_plugin
  notify:
    - Restart sirbot

- name: Clone plugin-slack repo
  become: true
  become_user: sirbot
  git:
    accept_hostkey: yes
    force: yes
    clone: yes
    repo: https://github.com/pyslackers/sirbot-slack.git
    version: master
    dest: /home/sirbot/sirbot-plugin-slack
  register: sirbot_clone_plugin_slack
  notify:
    - Restart sirbot

- name: Clone plugin-pythondev repo
  become: true
  become_user: sirbot
  git:
    accept_hostkey: yes
    force: yes
    clone: yes
    repo: https://github.com/pyslackers/sirbot-pythondev.git
    version: master
    dest: /home/sirbot/sirbot-plugin-pythondev
  register: sirbot_clone_plugin_pythondev
  notify:
    - Restart sirbot
