---
- name: Install necessary packages
  become: true
  apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - git
    - build-essential
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libncurses5-dev
    - libsqlite3-dev
    - libgdbm-dev
    - libdb-dev
    - libexpat1-dev
    - libpcap-dev
    - liblzma-dev
    - libpcre3-dev
    - libssl-dev

- name: Create sirbot user
  become: true
  user:
    name: sirbot
    shell: /bin/bash
    home: /user/sirbot

- name: Create virtualenv
  become: true
  become_user: sirbot
  pip:
    name: pip
    version: 9.0.1
    virtualenv: /home/sirbot/.pyvenv
    virtualenv_command: "/usr/local/pythonz/pythons/CPython-{{ python_version }}/bin/pyvenv"

- include: clone.yml

- include: install.yml

- name: Set sirbot in systemd
  become: true
  template:
    src: etc/systemd/system/sirbot.service.j2
    dest: /etc/systemd/system/sirbot.service
  notify:
    - Restart sirbot
    - Reload systemd dameon

- name: Start sirbot on boot
  become: true
  systemd:
    name: sirbot.service
    enabled: yes

- name: Database exist
  stat:
    path: /home/sirbot/sirbot.db
  register: sirbot_db

- name: Update sirbot
  become: true
  become_user: sirbot
  command: /home/sirbot/.pyvenv/bin/sirbot -c /home/sirbot/sirbot-plugin-pythondev/sirbot.yml --update
  environment:
    SIRBOT_SLACK_BOT_TOKEN: '0'
    SIRBOT_GITHUB_SECRET: 'a'
  when:
    - sirbot_db.stat.exists
    - sirbot_clone_core.changed or sirbot_clone_plugin.changed or sirbot_clone_plugin_slack.changed or sirbot_clone_plugin_pythondev.changed
  notify:
    - Restart sirbot
